trigger:
  branches:
    include:
      - main
      - master

pr:
  branches:
    include:
      - main
      - master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install .NET SDK
  inputs:
    packageType: sdk
    version: 8.x

- task: DotNetCoreCLI@2
  displayName: Restore project
  inputs:
    command: restore
    projects: 'Uhm.Framework.CalendarApp.Poc.Tests/Uhm.Framework.CalendarApp.Poc.Tests.csproj'
    feedsToUse: config
    nugetConfigPath: 'NuGet.Poc.Config'

- task: DotNetCoreCLI@2
  displayName: Build project
  inputs:
    command: build
    projects: 'Uhm.Framework.CalendarApp.Poc.Tests/Uhm.Framework.CalendarApp.Poc.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Run tests
  inputs:
    command: test
    projects: 'Uhm.Framework.CalendarApp.Poc.Tests/Uhm.Framework.CalendarApp.Poc.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build'
    publishTestResults: true
